add icon and crude ways of deleting profiles/devices/mappings
RawAccelOfficial/rawaccel pull request #251
Opened 2024-12-28 20:20 UTC by Sai-Moen

Adds a garbage bin icon for deleting things (taken from here https://avaloniaui.github.io/icons.html).
Adds buttons to delete profiles/devices/mappings from their respective ViewModels, deleting the underlying files will probably come later? As well as adding stuff in general.
The exact layout of things will definitely still change.

Also not sure if there is a more idiomatic MVVM way to do the deletes, but this seems to work at least.

2024-12-30 18:40 UTC, JacobPalecki requested changes

2024-12-30 18:40 UTC, JacobPalecki commented on userinterface/ViewModels/MappingsPageViewModel.cs
> +        public void DeleteMapping(BE.MappingModel mapping)
Deleting a backend item should be part of the interface exposed by backend to UI. So there should be a function within each BE class (Profiles, Mappings, Devices, DeviceGroups) called "Delete(specificItem)" that is called from the ViewModel. So let's add those functions and lift your current functionality to them from the ViewModel.

2024-12-31 17:03 UTC, Sai-Moen commented on userinterface/ViewModels/MappingsPageViewModel.cs
> +        public void DeleteMapping(BE.MappingModel mapping)
New commit adds Remove methods to profiles/devices/mappings/device groups Models and removes them from the ViewModels (if applicable).

2024-12-31 17:38 UTC, JacobPalecki approved these changes

2024-12-31 17:38 UTC, merged